ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE parishes ENABLE ROW LEVEL SECURITY;
ALTER TABLE priests ENABLE ROW LEVEL SECURITY;
ALTER TABLE masses ENABLE ROW LEVEL SECURITY;
ALTER TABLE altar_boys_masses ENABLE ROW LEVEL SECURITY;
ALTER TABLE altar_boy_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE religious_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE liturgical_items ENABLE ROW LEVEL SECURITY;